<?php
/**
 * @file
 * Trims HTML-enabled text to a set length without counting HTML tags.
 */

/**
 * Implements hook_field_formatter_info_alter().
 */
function field_html_trim_field_formatter_info_alter(&$info) {
  $supported = _field_html_trim_get_formatter_types();

  foreach ($supported as $type) {
    $info[$type]['settings']['enable_html_trim'] = FALSE;
    $info[$type]['settings']['html_trim']['exclude_html_from_trim_count'] = TRUE;
    $info[$type]['settings']['html_trim']['ellipsis'] = '...';
  }
}

/**
 * Implements hook_field_formatter_settings_form_alter().
 */
function field_html_trim_field_formatter_settings_form_alter(&$settings_form, $context) {
  $display = $context['instance']['display'][$context['view_mode']];
  $settings = $display['settings'];
  $supported = _field_html_trim_get_formatter_types();

  if (in_array($display['type'], $supported)) {
    $settings_form['enable_html_trim'] = array(
      '#type' => 'checkbox',
      '#title' => t('Enable HTML trim'),
      '#default_value' => $settings['enable_html_trim'],
    );
    $settings_form['html_trim'] = array(
      '#type' => 'container',
      '#states' => array(
        'visible' => array(
          ':input[name$="enable_html_trim]"]' => array('checked' => TRUE),
        ),
      ),
    );
    $settings_form['html_trim']['exclude_html_from_trim_count'] = array(
      '#type' => 'checkbox',
      '#title' => t('Exclude HTML tags from trim count'),
      '#default_value' => $settings['html_trim']['exclude_html_from_trim_count'],
    );
    $settings_form['html_trim']['exact'] = array(
      '#type' => 'checkbox',
      '#title' => t('Exact cut-off'),
      '#description' => t("If checked, string will be cut at character level. Otherwise, it'll be cut at word level."),
      '#default_value' => $settings['html_trim']['exact'],
    );
    $settings_form['html_trim']['ellipsis'] = array(
      '#type' => 'textfield',
      '#title' => t('Ellipsis to indicate text cut-off'),
      '#description' => t("Note: The ellipsis character length will be included in trim length."),
      '#default_value' => $settings['html_trim']['ellipsis'],
      '#size' => 4,
    );
  }
}

/**
 * Implements hook_field_formatter_settings_summary_alter().
 */
function field_html_trim_field_formatter_settings_summary_alter(&$summary, $context) {
  $display = $context['instance']['display'][$context['view_mode']];
  $settings = $display['settings'];
  $supported = _field_html_trim_get_formatter_types();

  if (in_array($display['type'], $supported)) {
    if ($settings['enable_html_trim']) {
      if ($settings['html_trim']['exclude_html_from_trim_count']) {
        $summary .= '<br />' . t('HTML tags excluded from trim count');
      }

      if ($settings['html_trim']['exact']) {
        $summary .= '<br />' . t('Cuts off at character level');
      }
      else {
        $summary .= '<br />' . t('Cuts off at word level');
      }
      if (!empty($settings['html_trim']['ellipsis'])) {
        $summary .= '<br />' . t('Append ellipsis: @ellipsis', array('@ellipsis' => $settings['html_trim']['ellipsis']));
      }
    }
  }
}

/**
 * Implements hook_field_attach_view_alter().
 */
function field_html_trim_field_attach_view_alter(&$output, $context) {
  $supported = _field_html_trim_get_formatter_types();

  foreach (element_children($output) as $field_name) {
    if (in_array($output[$field_name]['#formatter'], $supported)) {
      $element = &$output[$field_name];
      $instance = field_info_instance($element['#entity_type'], $field_name, $element['#bundle']);
      $settings = field_formatter_settings_get_instance_display_settings($element['#entity_type'], $field_name, $element['#bundle'], $element['#view_mode']);

      // Only proceed if HTML Trim is enabled.
      if (!$settings['enable_html_trim']) {
        continue;
      }

      foreach ($element['#items'] as $delta => $item) {
        // Only perform the actual trimming when no summary is used.
        if (!isset($item['summary']) || empty($item['summary'])) {
          if ($settings['html_trim']['exclude_html_from_trim_count']) {
            $safe_value = _text_sanitize($instance, $element['#language'], $item, 'value');
            $element[$delta]['#markup'] = _field_html_trim_get_trimmed_html($safe_value, $settings['trim_length'], $settings['html_trim']['ellipsis'], $settings['html_trim']['exact']);
          }
        }
      }
    }
  }
}

/**
 * Get supported formatter types.
 *
 * @return array
 *   An array of supported field API formatter types.
 */
function _field_html_trim_get_formatter_types() {
  return array(
    'text_trimmed',
    'text_summary_or_trimmed',
  );
}

/**
 * Returns trimmed HTML without counting HTML tags.
 *
 * @param string $safe_value
 *   The field's safe value to trim.
 * @param int $trim_length
 *   The length in characters to trim the value.
 * @param string $ellipsis
 *   The ellipsis to append after trimmed value.
 * @param bool $exact
 *   Whether or not to trim to character level.
 */
function _field_html_trim_get_trimmed_html($safe_value, $trim_length, $ellipsis, $exact) {
  // Variable for breakpoint checking.
  $breakpoint = strpos($safe_value, '<!--break-->');

  // If a breakpoint is defined...
  if ($breakpoint !== FALSE) {
    // Cut off the unwanted piece.
    $safe_value = strstr($safe_value, '<!--break-->', TRUE);
    // Put ellipsis inside of ending html tags.
    $safe_value = preg_replace('#^(.*)(\s?)(</[^>]+>)$#Us', '$1' . $ellipsis . '$3', $safe_value);
    // Return corrected output.
    return _filter_htmlcorrector($safe_value);
  }
  else {
    return field_html_trim_truncate($safe_value, $trim_length, array('ellipsis' => $ellipsis, 'exact' => $exact));
  }
}

/**
 * Truncates text.
 *
 * Cuts a string to the length of $length and replaces the last characters with
 * the ellipsis if the text is longer than length.
 * @link https://api.cakephp.org/3.5/class-Cake.Utility.Text.html#_truncate
 *
 * @param string $text
 *   String to truncate.
 * @param int $length
 *   Length of returned string, including ellipsis.
 * @param array $options
 *   An array of HTML attributes and options:
 *   - ellipsis: Will be used as ending and appended to the trimmed string.
 *   - exact: If FALSE, $text will not be cut mid-word.
 *   - html: If TRUE, HTML tags would be handled correctly.
 *
 * @return string
 *   Trimmed string.
 */
function field_html_trim_truncate($text, $length = 100, array $options = array()) {
  $default = array(
    'ellipsis' => '...',
    'exact' => TRUE,
    'html' => TRUE,
  );
  if (!empty($options['html']) && backdrop_strtolower(mb_internal_encoding()) === 'utf-8') {
    $default['ellipsis'] = "\xe2\x80\xa6";
  }
  $options += $default;
  extract($options);

  $text = trim(preg_replace('/\s\s+/', ' ', $text));
  if ($html) {
    if (backdrop_strlen(preg_replace('/<.*?>/', '', $text)) <= $length) {
      return $text;
    }

    $totalLength = backdrop_strlen(strip_tags($ellipsis));
    $openTags = array();
    $truncate = '';
    preg_match_all('/(<\/?([\w+]+)[^>]*>)?([^<>]*)/', $text, $tags, PREG_SET_ORDER);

    foreach ($tags as $tag) {
      if (!preg_match('/img|br|input|hr|area|base|basefont|col|frame|isindex|link|meta|param/s', $tag[2])) {
        if (preg_match('/<[\w]+[^>]*>/s', $tag[0])) {
          array_unshift($openTags, $tag[2]);
        }
        elseif (preg_match('/<\/([\w]+)[^>]*>/s', $tag[0], $closeTag)) {
          $pos = array_search($closeTag[1], $openTags);
          if ($pos !== FALSE) {
            array_splice($openTags, $pos, 1);
          }
        }
      }

      $truncate .= $tag[1];
      $contentLength = backdrop_strlen(preg_replace('/&[0-9a-z]{2,8};|&#[0-9]{1,7};|&#x[0-9a-f]{1,6};/i', ' ', $tag[3]));

      if ($contentLength + $totalLength > $length) {
        $left = $length - $totalLength;
        $entitiesLength = 0;

        if (preg_match_all('/&[0-9a-z]{2,8};|&#[0-9]{1,7};|&#x[0-9a-f]{1,6};/i', $tag[3], $entities, PREG_OFFSET_CAPTURE)) {
          foreach ($entities[0] as $entity) {
            if ($entity[1] + 1 - $entitiesLength <= $left) {
              $left--;
              $entitiesLength += backdrop_strlen($entity[0]);
            }
            else {
              break;
            }
          }
        }

        $truncate .= backdrop_substr($tag[3], 0, $left + $entitiesLength);
        break;
      }
      else {
        $truncate .= $tag[3];
        $totalLength += $contentLength;
      }

      if ($totalLength >= $length) {
        break;
      }
    }
  }
  else {
    if (backdrop_strlen($text) <= $length) {
      return $text;
    }

    $truncate = backdrop_substr($text, 0, $length - backdrop_strlen($ellipsis));
  }

  if (!$exact) {
    $spacepos = mb_strrpos($truncate, ' ');

    if ($html) {
      $truncateCheck = backdrop_substr($truncate, 0, $spacepos);
      $lastOpenTag = mb_strrpos($truncateCheck, '<');
      $lastCloseTag = mb_strrpos($truncateCheck, '>');

      if ($lastOpenTag > $lastCloseTag) {
        preg_match_all('/<[\w]+[^>]*>/s', $truncate, $lastTagMatches);
        $lastTag = array_pop($lastTagMatches[0]);
        $spacepos = mb_strrpos($truncate, $lastTag) + backdrop_strlen($lastTag);
      }

      $bits = backdrop_substr($truncate, $spacepos);
      preg_match_all('/<\/([a-z]+)>/', $bits, $droppedTags, PREG_SET_ORDER);

      if (!empty($droppedTags)) {
        if (!empty($openTags)) {
          foreach ($droppedTags as $closingTag) {
            if (!in_array($closingTag[1], $openTags)) {
              array_unshift($openTags, $closingTag[1]);
            }
          }
        }
        else {
          foreach ($droppedTags as $closingTag) {
            $openTags[] = $closingTag[1];
          }
        }
      }
    }

    $truncate = backdrop_substr($truncate, 0, $spacepos);
    // If truncate still empty, then we don't need to count ellipsis in the cut.
    if (backdrop_strlen($truncate) === 0) {
      $truncate = backdrop_substr($text, 0, $length);
    }
  }

  $truncate .= $ellipsis;

  if ($html) {
    foreach ($openTags as $tag) {
      $truncate .= '</' . $tag . '>';
    }
  }

  return $truncate;
}

